// Code generated by "stringer -type=Cloud enums.go"; DO NOT EDIT

package data

import "fmt"

const _Cloud_name = "DIGITAL_OCEANDOCKEROPENSTACK"

var _Cloud_index = [...]uint8{0, 13, 19, 28}

func (i CloudType) String() string {
	if i < 0 || i >= CloudType(len(_Cloud_index)-1) {
		return fmt.Sprintf("Cloud(%d)", i)
	}
	return _Cloud_name[_Cloud_index[i]:_Cloud_index[i+1]]
}
